spec-version: 0.30.0
name: hackcell
author: Patrick D. Elliott
maintainer: patrick.d.elliott@gmail.com
license: None

build-type: Simple

source-dirs: src
dependencies:
- { name: "base", version: '^>=4.13' }

ghc-options: -Wall
# default-extensions:
library: {}
executable:
  main: Main.hs
